# Annotation Transformer 配置
# 定义注解转换规则
commonAnnotations:
  - path: spec/template/metadata/annotations
    create: true
    version: apps/v1
    kind: Deployment
  - path: spec/template/metadata/annotations
    create: true
    version: apps/v1
    kind: StatefulSet
  - path: metadata/annotations
    create: true
    version: v1
    kind: Service

